export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const CAMERA_TRIGGER = "CAMERA_TRIGGER";
export const CAMERA_TRIGGER_SUCCESS = "CAMERA_TRIGGER_SUCCESS";
export const CAMERA_TRIGGER_FAILURE = "CAMERA_TRIGGER_FAILURE";

export const RUN_AUTOSETUP = "RUN_AUTOSETUP";
export const RUN_AUTOSETUP_SUCCESS = "RUN_AUTOSETUP_SUCCESS";
export const RUN_AUTOSETUP_FAILURE = "RUN_AUTOSETUP_FAILURE";

export const CAMERA_LOCAL_IMAGE = "CAMERA_LOCAL_IMAGE";

export const GET_TCP = "GET_TCP";
export const GET_TCP_SUCCESS = "GET_TCP_SUCCESS";
export const GET_TCP_FAILURE = "GET_TCP_FAILURE";

export const GET_ROBOT_PING = "GET_ROBOT_PING";
export const GET_ROBOT_PING_SUCCESS = "GET_ROBOT_PING_SUCCESS";
export const GET_ROBOT_PING_FAILURE = "GET_ROBOT_PING_FAILURE";

export const ROBOT_MODE_AUTO = "ROBOT_MODE_AUTO";
export const ROBOT_MODE_MANUAL = "ROBOT_MODE_MANUAL";
export const ROBOT_MODE_SUCCESS = "ROBOT_MODE_SUCCESS";
export const ROBOT_MODE_FAILURE = "ROBOT_MODE_FAILURE";

export const ROBOT_ENABLE = "ROBOT_ENABLE";
export const ROBOT_DISABLE = "ROBOT_DISABLE";
export const ROBOT_ENABLE_SUCCESS = "ROBOT_ENABLE_SUCCESS";
export const ROBOT_ENABLE_FAILURE = "ROBOT_ENABLE_FAILURE";

export const ROBOT_STOP = "ROBOT_STOP";
export const ROBOT_RESET = "ROBOT_RESET";
export const ROBOT_SAFETY_SUCCESS = "ROBOT_SAFETY_SUCCESS";
export const ROBOT_SAFETY_FAILURE = "ROBOT_SAFETY_FAILURE";

export const ROBOT_MOVEL = "ROBOT_MOVEL";
export const ROBOT_MOVEL_SUCCESS = "ROBOT_MOVEL_SUCCESS";
export const ROBOT_MOVEL_FAILURE = "ROBOT_MOVEL_FAILURE";

export const ANALYZE_IMAGE = "ANALYZE_IMAGE";
export const ANALYZE_IMAGE_SUCCESS = "ANALYZE_IMAGE_SUCCESS";
export const ANALYZE_IMAGE_FAILURE = "ANALYZE_IMAGE_FAILURE";

export const RESET_ANALYSIS = "RESET_ANALYSIS";

export const ROBOT_PICK_UNPICK = "ROBOT_PICK_UNPICK";
export const ROBOT_PICK_UNPICK_SUCCESS = "ROBOT_PICK_UNPICK_SUCCESS";
export const ROBOT_PICK_UNPICK_FAILURE = "ROBOT_PICK_UNPICK_FAILURE";

export const APP_PICKPLACE_START = "APP_PICKPLACE_START";
export const APP_PICKPLACE_START_SUCCESS = "APP_PICKPLACE_START_SUCCESS";
export const APP_PICKPLACE_START_FAILURE = "APP_PICKPLACE_START_FAILURE";

export const APP_PICKPLACE_STOP = "APP_PICKPLACE_STOP";
export const APP_PICKPLACE_STOP_SUCCESS = "APP_PICKPLACE_STOP_SUCCESS";
export const APP_PICKPLACE_STOP_FAILURE = "APP_PICKPLACE_STOP_FAILURE";

export const APP_PICKPLACE_STATUS = "APP_PICKPLACE_STATUS";
export const APP_PICKPLACE_STATUS_SUCCESS = "APP_PICKPLACE_STATUS_SUCCESS";
export const APP_PICKPLACE_STATUS_FAILURE = "APP_PICKPLACE_STATUS_FAILURE";

export const DXF_PREVIEW = "DXF_PREVIEW";
export const DXF_PREVIEW_SUCCESS = "DXF_PREVIEW_SUCCESS";
export const DXF_PREVIEW_FAILURE = "DXF_PREVIEW_FAILURE";

export const DXF_DRAW = "DXF_DRAW";
export const DXF_DRAW_SUCCESS = "DXF_DRAW_SUCCESS";
export const DXF_DRAW_FAILURE = "DXF_DRAW_FAILURE";

export const DXF_RESET = "DXF_RESET";

